const mongoose=require('mongoose');
const Courseschema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true
    },
    description:{
        type:String,
        required:true,
        trim:true,
    },
    language:{
        type:String,
        required:true,
        trim:true,
    },
    price:{
        type:Number,
        required:true,
    },
    whatwillyoulearn:{
        type:String,
        required:true,
        trim:true
    },
    studentsenrolled:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }],
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    sections:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Section"
    }],
    ratingsandreview:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Ratings"
    }],
    thumbnail:{
        type:String,
        require:true
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Category"
    },
    tags:[{
        type:String,
        required:true
    }],
    status:{
        type:String,
        required:true,
        enum:["Draft","Published"],
        default:"Draft"
    },
    createdat:{
        type:Date,
        required:true,
        default:Date.now()
    },
    requirements:[{
        type:String,
        required:true
    }]
    
})

module.exports=mongoose.model("Course",Courseschema);